### ISSUE TITLE
Volume down knock action

### ISSUE THREAD

**Issue by gabrielfeo** [hardastyle/tipSkipMOD#1]
Hello hardastyle,

First of all, thank you for introducing me to this app, it's really not as known as it should be. It's even better with tipSkipMOD.
I love the "Volume Up" option, but could you please add Volume Down as a possible knock action? Maybe through adding a GUI to the mod and giving a choice of replacing "Next" or "Previous" with "Volume Down". I'd really appreciate it. Thanks!

Best regards,
Gabriel.

**Comment by 1LineAtaTime** [comment]
Hi Gfeo, I'm glad you got to discover this app and also liked the module. 
About your request, sure thing!
I'll add a GUI where it will allow the user to change each and every knock option with the Volume-Up or Volume-Down :)

**Comment by gabrielfeo** [comment]
Thanks!

**Comment by 1LineAtaTime** [comment]
Sadly, after some hours of work, I haven't been able to figure out how to use the Shared Preferences for Android to save the given input from the GUI and use it in the Xposed hook.
If you know how to code it, feel free to create a pull request with the modified stuff and I will add it to the github and Xposed repository (+ the credits where they belong).
Again, sorry about that.

**Comment by jorgsiegel** [comment]
Hi guys, we are the developers of the app and really appreciate your feedback that we found by coincidence. We worked on a new version (beautiful design, better algorithm, more features) the last two months and will release it in a couple of days/weeks, most likely before the end of July.
Your considerations will be in the app:
-the splash screen only lasts for around 1sec (only at the very first start, one time, it is 2secs)
-the volume up/down option can be selected in the settings

**Comment by 1LineAtaTime** [comment]
Wow, you really are awesome! Thank you for such an amazing app!!
